### ISSUE TITLE
Could you tell me how to access the CCDD?

### ISSUE THREAD

**Issue by JianqiaoAirport** [LuZhenHuan/code#1]
Thank you so much for your work! Currently I am interested in arrythmia classification, too. But I cannot find the CCDD on the Internet, could you tell me  how to access the CCDD or download it?

Thanks again.

**Comment by LuZhenHuan** [comment]
The CCDD data is here: http://58.210.56.164/ccdd/ 
But this site is often inaccessible
So when i want to use it, i first contacted the administrator teacher, Prof. Dong.You should try this.
E-mail: jdong2010@sinano.ac.cn
All the information is in this paper ’Deep learning research on clinical electrocardiogram analysis‘
Hope this helps.

**Comment by JianqiaoAirport** [comment]
OK, I will try it later. Thank you very much!
