### ISSUE TITLE
ecg data request

### ISSUE THREAD

**Issue by JoaquinXu** [LuZhenHuan/code#3]
Hi, Lu, this is Joaquin. Thanks for you sharing your codes here. What you did is very consistent with my master's topic, I want to run the codes by myself to have a better understanding. The CCDD dataset now needs request right, I already sent the email to the data's administrator, but up to now, there is no reply. Could you please send me the data to my mailbox, my mailbox is 774893095@qq.com. Really appreciate your help. Thanks.

**Comment by LuZhenHuan** [comment]
Sorry guys, I have graduated for a long time, and my data has been stored in the school, so I have no data now, I guess you can only wait for the CCDD to reply

**Comment by JoaquinXu** [comment]
Ok bro, thanks for your honest reply. I will keep trying to access the data. Wish you a good day.


发自我的iPhone

------------------ Original ------------------
